version: 0.2
# https://docs.aws.amazon.com/codebuild/latest/userguide/getting-started.html
phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed on `date`
      - cp target/reciter-scopus-retrieval-tool-1.1.0.jar .
artifacts:
  files:
    - reciter-scopus-retrieval-tool-1.1.0.jar
    - .ebextensions/**/* 
    - Procfile